#!/bin/sh
# 
#  timediff - show time differences at the place
#
#  Copyright (c) 2016 Masato Minda
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
#  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
#  FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
#  DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
#  OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
#  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
#  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
#  OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
#  SUCH DAMAGE.
#
#  $Id: timediff,v 1.18 2016/08/02 21:40:52 minmin Exp $

format='%F %R %Z'
max=10

__check_match () {
	if [ `echo ${1} | wc -w` -eq 1 ]
	then
		return 0
	fi
	ls -dF ${1}
	exit 1
}

__set_zoneinfo () {

	case "${1}" in
	*\**)
		__check_match "${1}*"
		zi=`echo ${1}*`
		;;

	*)	zi=${1}
		;;
	esac

	while [ ! -f ${zi} ]
	do
		if [ -d ${zi} ]; then
			ls -dF ${zi}/*
			exit 1
		fi

		__check_match "${zi}*"
		zi=`echo ${zi}*`
		if [ ! -e ${zi} ]; then
			__check_match "*/${zi}"
			zi=`echo */${zi}`
			if [ ! -e ${zi} ]; then
				__check_match "*/${zi}"
				zi=`echo */${zi}`
				if [ ! -e ${zi} ]; then
					ls -F
					exit 2
				fi
			fi
		fi
	done
}

__usage () {
	echo "Usage: ${0##*/} zoneinfo [ count ]" 1>&2
	exit 2
}

cd /usr/share/zoneinfo || exit

if [ $# -eq 0 ]; then
	ls -F
	exit
elif [ $# -eq 1 ]; then
	case ${1} in
	-*) __usage ;;
	esac
elif [ $# -ge 3 ]; then
	__usage
elif [ ${2} -gt  0 ]; then
	max=${2}
fi

__set_zoneinfo "${1}"

ut=$(( (`date +%s`/3600)*3600 ))

echo ${zi}

if type jot >/dev/null 2>&1
then
	# this system has 'jot', it may be *BSD or macOS
	for i in `jot ${max} 0`
	do
		remote=`TZ=${zi} date -r ${ut} +"${format}"`
		local=`date -r ${ut} +"${format}"`
		echo ${remote}'     '${local}
		ut=$((ut + 3600))
	done
else
	# this system does not have 'jot', it may be Linux box.
	for i in `seq 1 ${max}`
	do
		remote=`TZ=${zi} date --date=@${ut} +"${format}"`
		local=`date --date=@${ut} +"${format}"`
		echo ${remote}'     '${local}
		ut=$((ut + 3600))
	done
fi
