#!/bin/sh
# 
#  timediff - show time differences at the place
#
#  Copyright (c) 2016 Masato Minda
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
#  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
#  FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
#  DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
#  OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
#  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
#  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
#  OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
#  SUCH DAMAGE.
#
#  $Id: timediff,v 1.24 2017/05/11 15:39:26 minmin Exp $

format='%F %R %Z'
max=10

__check_match () {
	if [ `echo ${1} | wc -w` -eq 1 ]
	then
		return 0
	fi
	ls -dF ${1}
	exit 1
}

__set_zoneinfo () {

	case "${1}" in
	*\**)
		__check_match "${1}*"
		zi=`echo ${1}*`
		;;

	*)	zi=${1}
		;;
	esac

	while [ ! -f ${zi} ]
	do
		if [ -d ${zi} ]; then
			ls -dF ${zi}/*
			exit 1
		fi

		__check_match "${zi}*"
		zi=`echo ${zi}*`
		if [ ! -e ${zi} ]; then
			__check_match "*/${zi}"
			zi=`echo */${zi}`
			if [ ! -e ${zi} ]; then
				__check_match "*/${zi}"
				zi=`echo */${zi}`
				if [ ! -e ${zi} ]; then
					ls -F
					exit 2
				fi
			fi
		fi
	done
}

__usage () {
	echo "Usage: ${0##*/} zoneinfo [zoneinfo... ] [count] [0]" 1>&2
	exit 2
}

cd /usr/share/zoneinfo || exit

while getopts '0h' cmd_arg
do
        case "${cmd_arg}" in
        0)      zero_flag=YES ;;
        h|*)    __usage ;;
        esac
done >&2

shift $((OPTIND - 1))

if [ $# -eq 0 ]; then
	ls -F
	exit
fi

id=0

while [ $# -gt 0 ]
do
	case $1 in

	[0-9]*)
		if [ ${1} -eq 0 ]; then
			zero_flag=YES
		else
			max=${1}
		fi
		;;
	*)
		__set_zoneinfo "${1}"
		eval tz${id}=${zi}
		id=$((id + 1))
		;;
	esac
	shift
done

if [ ${id} -eq 0 ]
then
	__usage
fi

if [ x${zero_flag} = x"YES" ]; then
	ut=$(( (`date +%s`/3600)*3600 ))
else
	ut=`date +%s`
fi

i=0
while [ ${i} -lt ${id} ]
do
	eval tz=\$tz${i}
	printf "$tz\t"
	i=$((i + 1))
done
echo ''

if type jot >/dev/null 2>&1
then
	# this system has 'jot', it may be *BSD or macOS
	for i in `jot ${max} 0`
	do
		i=0
		while [ ${i} -lt ${id} ]
		do
			eval tz=\$tz${i}
			remote=`TZ=${tz} date -r ${ut} +"${format}"`
			printf "${remote}\t"
			i=$((i + 1))
		done
		date -r ${ut} +"${format}"
		ut=$((ut + 3600))
	done
else
	# this system does not have 'jot', it may be Linux box.
	for i in `seq 1 ${max}`
	do
		i=0
		while [ ${i} -lt ${id} ]
		do
			eval tz=\$tz${i}
			remote=`TZ=${tz} date --date=@${ut} +"${format}"`
			printf "${remote}\t"
			i=$((i + 1))
		done
		date --date=@${ut} +"${format}"
		ut=$((ut + 3600))
	done
fi
